// Minimum number of entity for arrangement to be valid!
const minimumEntityCount = 1;
// Maximum number of entity for arrangement to be valid!
const maximumEntityCount = 8;
// Maximum number of characters a name of an entity has!
const maximumCharCount = 15;

// 100 male names sorted alphabetically, used for random initializations!
const maleNames = [
  "Adam",
  "Apollo",
  "Archie",
  "Bailey",
  "Bandit",
  "Baxter",
  "Bear",
  "Beau",
  "Benji",
  "Benny",
  "Bentley",
  "Blue",
  "Bo",
  "Boomer",
  "Brady",
  "Brody",
  "Bruno",
  "Brutus",
  "Bubba",
  "Buddy",
  "Buster",
  "Champ",
  "Chance",
  "Charlie",
  "Chase",
  "Chester",
  "Chico",
  "Chiku",
  "Cody",
  "Cooper",
  "Copper",
  "Dexter",
  "Dom",
  "Duke",
  "Elvis",
  "Eric",
  "Finn",
  "Frankie",
  "Gambit",
  "George",
  "Gizmo",
  "Gunner",
  "Gus",
  "Hank",
  "Henry",
  "Hunter",
  "Jack",
  "Jackson",
  "Jake",
  "Jasper",
  "Jax",
  "Jov",
  "Joey",
  "Kobe",
  "Leo",
  "Loki",
  "Louie",
  "Luke",
  "Mac",
  "Matthew",
  "Max",
  "Mickey",
  "Milo",
  "Moose",
  "Murphy",
  "Nathan",
  "Oliver",
  "Ollie",
  "Oreo",
  "Oscar",
  "Otis",
  "Prince",
  "Rex",
  "Riley",
  "Rocco",
  "Rocky",
  "Romeo",
  "Roscoe",
  "Rudy",
  "Rufus",
  "Rusty",
  "Sam",
  "Sammy",
  "Samson",
  "Scooter",
  "Scout",
  "Simba",
  "Sparky",
  "Spike",
  "Tank",
  "Teddy",
  "Thor",
  "Toby",
  "Tom",
  "Tucker",
  "Tyson",
  "Walter",
  "Winston",
  "Zeus",
  "Ziggy",
];

// 100 female names sorted alphabetically, used for random initializations!
const femaleNames = [
  "Abby",
  "Allie",
  "Angel",
  "Annie",
  "Athena",
  "Ava",
  "Baby",
  "Bella",
  "Belle",
  "Bonnie",
  "Brandy",
  "Cali",
  "Callie",
  "Casey",
  "Chloe",
  "Cleo",
  "Coco",
  "Cocoa",
  "Cookie",
  "Daisy",
  "Dakota",
  "Dixie",
  "Ella",
  "Ellie",
  "Emma",
  "Gigi",
  "Ginger",
  "Grace",
  "Gracie",
  "Hannah",
  "Harley",
  "Hazel",
  "Heidi",
  "Holly",
  "Honey",
  "Izzy",
  "Jasmine",
  "Joan",
  "Josie",
  "Katie",
  "Kona",
  "Lacey",
  "Lady",
  "Layla",
  "Lexi",
  "Lexie",
  "Lilly",
  "Lily",
  "Lola",
  "Lucky",
  "Lucy",
  "Lulu",
  "Luna",
  "Macy",
  "Maddie",
  "Maeve",
  "Maggie",
  "Marley",
  "Maya",
  "Mia",
  "Millie",
  "Mimi",
  "Minnie",
  "Missy",
  "Misty",
  "Mocha",
  "Molly",
  "Mystique",
  "Nala",
  "Nikki",
  "Ola",
  "Olivia",
  "Peanut",
  "Pebbles",
  "Penny",
  "Pepper",
  "Phoebe",
  "Piper",
  "Princess",
  "Rosie",
  "Roxie",
  "Roxy",
  "Ruby",
  "Sadie",
  "Sally",
  "Samantha",
  "Sasha",
  "Sassy",
  "Shadow",
  "Shelby",
  "Sierra",
  "Sophie",
  "Stella",
  "Sugar",
  "Sylvie",
  "Trixie",
  "Willow",
  "Winnie",
  "Zoe",
  "Zoya",
];

// Initial names taken ->
// Male: Baxter,Eric,Jov,Loki,Otis
// Female: Emma,Jasmine,Maeve,Sylvie,Zoe

// Default arrangement
const defaultArrangement = {
  male: [
    {
      name: "Chiku",
      preferences: ["Emma", "Jasmine", "Maeve", "Sylvie", "Zoe"],
    },
    {
      name: "Eric",
      preferences: ["Zoe", "Maeve", "Sylvie", "Jasmine", "Emma"],
    },
    {
      name: "Jov",
      preferences: ["Jasmine", "Zoe", "Maeve", "Emma", "Sylvie"],
    },
    {
      name: "Loki",
      preferences: ["Sylvie", "Maeve", "Jasmine", "Emma", "Zoe"],
    },
    {
      name: "Otis",
      preferences: ["Maeve", "Jasmine", "Emma", "Sylvie", "Zoe"],
    },
  ],
  female: [
    {
      name: "Emma",
      preferences: ["Chiku", "Eric", "Jov", "Loki", "Otis"],
    },
    {
      name: "Jasmine",
      preferences: ["Loki", "Jov", "Eric", "Chiku", "Otis"],
    },
    {
      name: "Maeve",
      preferences: ["Eric", "Otis", "Loki", "Jov", "Chiku"],
    },
    {
      name: "Sylvie",
      preferences: ["Loki", "Otis", "Chiku", "Eric", "Jov"],
    },
    {
      name: "Zoe",
      preferences: ["Eric", "Jov", "Loki", "Otis", "Chiku"],
    },
  ],
};

export {
  minimumEntityCount,
  maximumEntityCount,
  maximumCharCount,
  defaultArrangement,
  maleNames,
  femaleNames,
};
